/**
 * Shows and changes the production business settings — the Firestore document `config/app`
 * (src/shared/settings.ts lists every key, its default and allowed range). Local testing uses SETTING_* in the
 * repo-root .env instead, so this script is for the real project only.
 *
 * Local only, like create-admin.ts — needs the service account key in functions/.env.scripts.
 *
 * Usage (from the repo root):
 *   make settings-show
 *   make settings-set KEY=otpMaxSendsPerHour VALUE=4
 *   make settings-seed        # writes every missing key with its default; never overwrites a set value
 *   make settings-pull        # copies the production values into the repo-root .env.pulled for the local backend
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { config } from 'dotenv';

// NOT functions/.env — see create-admin.ts.
config({ path: path.resolve(__dirname, '../.env.scripts') });

import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

import { parseSetting, resolveSettings, settingEnvName, SETTINGS, SETTINGS_DOC_PATH, type SettingKey } from '../src/shared/settings';

// The local Docker backend loads this after .env (docker-compose.yml), so what's pulled wins over SETTING_* there.
const PULLED_ENV_PATH = path.resolve(__dirname, '../../.env.pulled');
const PULLED_BEGIN = '# >>> pulled from production Firestore config/app — regenerated by `make settings-pull`, do not edit';
const PULLED_END = '# <<< end of pulled block — add your own lines below; they are kept and override the block';

/**
 * Rewrites the pulled block of .env.pulled and keeps every other line, so variables added by hand survive a re-pull.
 * The block holds every known setting (its effective production value) plus any extra primitive field in the doc, so
 * a setting added in production before this code knows it still comes along.
 */
function writePulledEnv(stored: Record<string, unknown>, project: string) {
  const effective = resolveSettings(stored);
  const lines = [PULLED_BEGIN, `# project: ${project}, pulled: ${new Date().toISOString()}`];

  for (const name of Object.keys(SETTINGS) as SettingKey[]) {
    if (parseSetting(name, stored[name]) === undefined) {
      lines.push(name in stored ? `# ${name}: INVALID in production, so the default is used` : `# ${name}: not set in production, so the default`);
    }
    lines.push(`${settingEnvName(name)}=${effective[name]}`);
  }
  for (const [name, value] of Object.entries(stored)) {
    if (name in SETTINGS || !['string', 'number', 'boolean'].includes(typeof value)) continue;
    lines.push(`# ${name}: not a known setting yet (add it to src/shared/settings.ts to use it)`, `${settingEnvName(name as SettingKey)}=${value}`);
  }
  lines.push(PULLED_END);

  const existing = existsSync(PULLED_ENV_PATH) ? readFileSync(PULLED_ENV_PATH, 'utf8') : '';
  const begin = existing.indexOf(PULLED_BEGIN);
  const endAt = existing.indexOf(PULLED_END);
  const kept = begin !== -1 && endAt > begin
    ? existing.slice(0, begin) + existing.slice(endAt + PULLED_END.length)
    : existing; // no block yet (or a mangled one): keep the whole file, the fresh block goes on top
  writeFileSync(PULLED_ENV_PATH, `${lines.join('\n')}\n${kept.replace(/^\n+/, '')}`);
  return lines.filter((line) => !line.startsWith('#')).length;
}

const isSettingKey = (key: string | undefined): key is SettingKey => Boolean(key && key in SETTINGS);

async function main() {
  const [command, key, value] = process.argv.slice(2);
  const ref = getFirestore(initializeApp()).doc(SETTINGS_DOC_PATH);
  const stored = (await ref.get()).data() ?? {};

  if (command === 'show') {
    const effective = resolveSettings(stored);
    for (const name of Object.keys(SETTINGS) as SettingKey[]) {
      const source = parseSetting(name, stored[name]) !== undefined ? 'set' : name in stored ? 'INVALID, using default' : 'default';
      console.log(`${name.padEnd(26)} ${String(effective[name]).padEnd(12)} (${source}) — ${SETTINGS[name].description}`);
    }
    return;
  }

  if (command === 'set') {
    if (!isSettingKey(key)) throw new Error(`Unknown setting "${key}". Known: ${Object.keys(SETTINGS).join(', ')}`);
    const parsed = parseSetting(key, value);
    if (parsed === undefined) {
      const spec = SETTINGS[key];
      throw new Error(`"${value}" isn't allowed for ${key} (${'min' in spec ? `whole number ${spec.min}–${spec.max}` : `must match ${spec.pattern}`}).`);
    }
    await ref.set({ [key]: parsed }, { merge: true });
    console.log(`${key} = ${parsed}. Apps pick it up on their next launch, functions within a minute.`);
    return;
  }

  if (command === 'seed') {
    const missing = Object.fromEntries(
      (Object.keys(SETTINGS) as SettingKey[]).filter((name) => parseSetting(name, stored[name]) === undefined).map((name) => [name, SETTINGS[name].default]),
    );
    await ref.set(missing, { merge: true });
    console.log(Object.keys(missing).length ? `Wrote defaults for: ${Object.keys(missing).join(', ')}` : 'Every setting is already set.');
    return;
  }

  if (command === 'pull') {
    const count = writePulledEnv(stored, process.env.GCLOUD_PROJECT ?? '?');
    console.log(`Wrote ${count} settings to ${PULLED_ENV_PATH}. \`make backend-restart\` (or make local-apks) applies them.`);
    return;
  }

  console.error('Usage: npm run settings -- show | set <key> <value> | seed | pull');
  process.exit(1);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
